development:
  access_key_id: AKIAIBLENOTBK7XPBWQA
  secret_access_key: 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

test:
  access_key_id: AKIAIBLENOTBK7XPBWQA
  secret_access_key: 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

production:
  access_key_id: AKIAIBLENOTBK7XPBWQA
  secret_access_key: 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
