addresses:
  single: &single_address
    data:
      id: 42
      type: "addresses"
      attributes:
        latitude: 55.947064
        longitude: 37.4992755000001
        address: "Russia, Moscow, Lenina Str, 42, 213230"
        short_address: "Lenina Str, 42"
        name: "Ivan"
        phone: "+79654242424"
  multiple:
    data:
      -
        <<: *single_address
complains:
  single: &single_complain
    data:
      id: 42
      type: "complains"
      attributes:
        subject: "Very bad courier"
        body: "Lates more then a day"
        resolution: null
        status: "opened"
      relationships:
        from:
          data:
            id: 42
            type: "people"
        to:
          data:
            id: 42
            type: "couriers"
        order:
          data:
            id: 42
            type: "orders"
        operator:
          data:
            id: 42
            type: "operators"
  multiple:
    data:
      -
        <<: *single_complain
    meta:
      total_pages: 10
      total_objects: 100
      page: 1
      per_page: 10
deals:
  single: &single_deal
    data:
      id: 42
      type: "deals"
      attributes:
        status: "in_progress"
        delivered_at: null
        created_at: "2016-01-12T17:33:03.661Z"
        updated_at: "2016-01-12T17:33:03.661Z"
      relationships:
        order:
          data:
            id: 42
            type: "orders"
        to:
          courier:
            id: 42
            type: "couriers"
  multiple:
    data:
      -
        <<: *single_deal
transports:
  single: &single_transport
    data:
      id: 42
      type: "transports"
      attributes:
        name: "Bicycle"
  multiple:
    data:
      -
        <<: *single_transport
orders:
  single: &single_order
    data:
      id: 42
      type: "orders"
      attributes:
        status: "closed"
        name: "order"
        description: "description"
        value: 100
        price: 123
        weight: 3
        grab_from: "2016-01-16T00:17:00.000Z"
        grab_to: "2016-01-20T03:00:00.000Z"
        deliver_from: "2016-01-19T04:00:00.000Z"
        deliver_to: "2016-01-29T04:00:00.000Z"
        created_at: "2016-01-15T21:17:58.024Z"
        delivered_at: delivered time
      relationships:
        person:
          data:
            id: 42
            type: "person"
        deals:
          -
            id: 42
            type: "deals"
        addresses:
          -
            id: 42
            type: "addresses"
        transports:
          -
            id: 42
            type: "transports"
        from_address:
          id: 42
          type: "addresses"
  multiple:
    data:
      -
        <<: *single_order
    meta:
      total_pages: 10
      total_objects: 100
      page: 1
      per_page: 10
people: &people
  single: &single_person
    data:
      id: 42
      type: "people"
      attributes:
        name: "order"
        email: "email"
        type: "Person"
        picture: "picture_url"
      relationships:
        orders:
          -
            data:
              id: 42
              type: "orders"
        addresses:
          -
            data:
              id: 42
              type: "addresses"
  multiple:
    data:
      -
        <<: *single_person
couriers:
  single: &single_person
    data:
      id: 42
      type: "couriers"
      attributes:
        name: "order"
        email: "email"
        type: "Corier"
        picture: "picture_url"
      relationships:
        finished_activities:
          -
            data:
              id: 42
              type: "activities"

  multiple:
    data:
      -
        <<: *single_person
    meta:
      total_pages: 10
      total_objects: 100
      page: 1
      per_page: 10
operators:
  single: &single_operator
    data:
      id: 42
      type: "operators"
      attributes:
        name: "order"
        email: "email"
        type: "Operator"
        picture: "picture_url"
  multiple:
    data:
      -
        <<: *single_operator
users:
  <<: *people
activities:
  single: &single_activity
    data:
      id: 42
      type: activities
      attributes:
        minutes: 30
        start: start_time
        finish: finish_time
      relationships:
        courier:
          data:
            id: 42
            type: "couriers"
        completed_deals:
          data:
            id: 42
            type: "deals"
  multiple:
    data:
      -
        <<: *single_activity
