default: &default
  adapter: postgresql
  username: postgres
  encoding: utf8
  pool: 8

production:
  <<: *default
  database: {{ name }}_production

iwant_users_production:
  <<: *default
  database: iwant_users_production
