production:
  secret_key_base: 17a3ccfb5498092290e306577b696363345c2e1dfac58f89b5ac5f6145288c2457eba161e5f3d97c79baba0dc70c8b45d1fe3df273eb0af7f45933b9371f47bc
  host: localhost
  port: 8080
  url: http://localhost
  ui_host:  http://localhost
  ui_password_path: /password
  apidoc_username: username
  apidoc_password: password
  aws_config:
    bucket: iwantdatadata
